import { createSlice } from '@reduxjs/toolkit';

// createSlice replaces both actions.js and reducer.js
const patientSlice = createSlice({
  name: 'patient',
  initialState: { patients: [] },
  reducers: {
    // No need to write action types manually — RTK auto-creates them
    addPatient: (state, action) => {
      state.patients.push(action.payload);
    },
    deletePatient: (state, action) => {
      state.patients = state.patients.filter((_, index) => index !== action.payload);
    },
  },
});

// Export actions (auto-generated by RTK)
export const { addPatient, deletePatient } = patientSlice.actions;

// Export reducer
export default patientSlice.reducer;
